**Atualizando a biblioteca para plotagem de gráficos**


In [90]:
# !pip -q install plotly --upgrade
# !pip install -U scikit-learn
# !pip install pandas
# !pip install seaborn

**Importando bibliotecas**

In [91]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, OneHotEncoder
import matplotlib.pyplot as plt
import plotly.express as px

**Abrindo um arquivo CSV do drive**

In [92]:
base = pd.read_csv('breast-cancer.csv', sep=',')

**Você também pode carregar seu arquivo e já selecionar as colunas que desejar... investigue esta função**

In [93]:
#base2 = pd.read_csv('/content/sample_data/restaurante.csv', ';', usecols=['Alternativo', 'Bar'])
#base2

In [94]:
oe = OrdinalEncoder(categories=[['0-4','5-9','10-14','15-19', '20-24', '25-29', '30-34', '35-39', '40-44','45-49','50-54']])
base['tumor-size'] = oe.fit_transform(base[['tumor-size']])
base


age menopause  tumor-size inv-nodes node-caps  deg-malig breast  \
0    40-49   premeno         3.0       0-2       yes          3  right   
1    50-59      ge40         3.0       0-2        no          1  right   
2    50-59      ge40         7.0       0-2        no          2   left   
3    40-49   premeno         7.0       0-2       yes          3  right   
4    40-49   premeno         6.0       3-5       yes          2   left   
..     ...       ...         ...       ...       ...        ...    ...   
281  50-59      ge40         6.0       6-8       yes          2   left   
282  50-59   premeno         5.0       3-5       yes          2   left   
283  30-39   premeno         6.0       6-8       yes          2  right   
284  50-59   premeno         3.0       0-2        no          2  right   
285  50-59      ge40         8.0       0-2        no          3   left   

    breast-quad irradiat                 Class  
0       left_up       no     recurrence-events  
1       central       no  no-recurrence-events  
2      left_low       no     recurrence-events  
3      left_low      yes  no-recurrence-events  
4      right_up       no     recurrence-events  
..          ...      ...                   ...  
281    left_low       no  no-recurrence-events  
282    left_low      yes  no-recurrence-events  
283    right_up       no  no-recurrence-events  
284    left_low       no  no-recurrence-events  
285    right_up       no  no-recurrence-events  

[286 rows x 10 columns]

In [95]:
le = LabelEncoder()
base['node-caps'] = le.fit_transform(base['node-caps'])
base['breast'] = le.fit_transform(base['breast'])
base['menopause'] = le.fit_transform(base['menopause'])
base['irradiat'] = le.fit_transform(base['irradiat'])
base['Class'] = le.fit_transform(base['Class'])
base

age  menopause  tumor-size inv-nodes  node-caps  deg-malig  breast  \
0    40-49          2         3.0       0-2          2          3       1   
1    50-59          0         3.0       0-2          1          1       1   
2    50-59          0         7.0       0-2          1          2       0   
3    40-49          2         7.0       0-2          2          3       1   
4    40-49          2         6.0       3-5          2          2       0   
..     ...        ...         ...       ...        ...        ...     ...   
281  50-59          0         6.0       6-8          2          2       0   
282  50-59          2         5.0       3-5          2          2       0   
283  30-39          2         6.0       6-8          2          2       1   
284  50-59          2         3.0       0-2          1          2       1   
285  50-59          0         8.0       0-2          1          3       0   

    breast-quad  irradiat  Class  
0       left_up         0      1  
1       central         0      0  
2      left_low         0      1  
3      left_low         1      0  
4      right_up         0      1  
..          ...       ...    ...  
281    left_low         0      0  
282    left_low         1      0  
283    right_up         0      0  
284    left_low         0      0  
285    right_up         0      0  

[286 rows x 10 columns]

In [96]:
one = OneHotEncoder(sparse_output=False)
encoded = pd.DataFrame(one.fit_transform(base[['breast-quad']]),columns=one.get_feature_names_out(['breast-quad']))
encoded

breast-quad_?  breast-quad_central  breast-quad_left_low  \
0              0.0                  0.0                   0.0   
1              0.0                  1.0                   0.0   
2              0.0                  0.0                   1.0   
3              0.0                  0.0                   1.0   
4              0.0                  0.0                   0.0   
..             ...                  ...                   ...   
281            0.0                  0.0                   1.0   
282            0.0                  0.0                   1.0   
283            0.0                  0.0                   0.0   
284            0.0                  0.0                   1.0   
285            0.0                  0.0                   0.0   

     breast-quad_left_up  breast-quad_right_low  breast-quad_right_up  
0                    1.0                    0.0                   0.0  
1                    0.0                    0.0                   0.0  
2                    0.0                    0.0                   0.0  
3                    0.0                    0.0                   0.0  
4                    0.0                    0.0                   1.0  
..                   ...                    ...                   ...  
281                  0.0                    0.0                   0.0  
282                  0.0                    0.0                   0.0  
283                  0.0                    0.0                   1.0  
284                  0.0                    0.0                   0.0  
285                  0.0                    0.0                   1.0  

[286 rows x 6 columns]

**Contando quantidade de instâncias**


In [97]:
base = base.drop('breast-quad', axis=1)
base = pd.concat([base,encoded],axis=1)
base

age  menopause  tumor-size inv-nodes  node-caps  deg-malig  breast  \
0    40-49          2         3.0       0-2          2          3       1   
1    50-59          0         3.0       0-2          1          1       1   
2    50-59          0         7.0       0-2          1          2       0   
3    40-49          2         7.0       0-2          2          3       1   
4    40-49          2         6.0       3-5          2          2       0   
..     ...        ...         ...       ...        ...        ...     ...   
281  50-59          0         6.0       6-8          2          2       0   
282  50-59          2         5.0       3-5          2          2       0   
283  30-39          2         6.0       6-8          2          2       1   
284  50-59          2         3.0       0-2          1          2       1   
285  50-59          0         8.0       0-2          1          3       0   

     irradiat  Class  breast-quad_?  breast-quad_central  \
0           0      1            0.0                  0.0   
1           0      0            0.0                  1.0   
2           0      1            0.0                  0.0   
3           1      0            0.0                  0.0   
4           0      1            0.0                  0.0   
..        ...    ...            ...                  ...   
281         0      0            0.0                  0.0   
282         1      0            0.0                  0.0   
283         0      0            0.0                  0.0   
284         0      0            0.0                  0.0   
285         0      0            0.0                  0.0   

     breast-quad_left_low  breast-quad_left_up  breast-quad_right_low  \
0                     0.0                  1.0                    0.0   
1                     0.0                  0.0                    0.0   
2                     1.0                  0.0                    0.0   
3                     1.0                  0.0                    0.0   
4                     0.0                  0.0                    0.0   
..                    ...                  ...                    ...   
281                   1.0                  0.0                    0.0   
282                   1.0                  0.0                    0.0   
283                   0.0                  0.0                    0.0   
284                   1.0                  0.0                    0.0   
285                   0.0                  0.0                    0.0   

     breast-quad_right_up  
0                     0.0  
1                     0.0  
2                     0.0  
3                     0.0  
4                     1.0  
..                    ...  
281                   0.0  
282                   0.0  
283                   1.0  
284                   0.0  
285                   1.0  

[286 rows x 15 columns]

In [98]:
oe = OrdinalEncoder(categories=[['20-29','30-39','40-49','50-59', '60-69', '70-79']])
base['age'] = oe.fit_transform(base[['age']])
base

age  menopause  tumor-size inv-nodes  node-caps  deg-malig  breast  \
0    2.0          2         3.0       0-2          2          3       1   
1    3.0          0         3.0       0-2          1          1       1   
2    3.0          0         7.0       0-2          1          2       0   
3    2.0          2         7.0       0-2          2          3       1   
4    2.0          2         6.0       3-5          2          2       0   
..   ...        ...         ...       ...        ...        ...     ...   
281  3.0          0         6.0       6-8          2          2       0   
282  3.0          2         5.0       3-5          2          2       0   
283  1.0          2         6.0       6-8          2          2       1   
284  3.0          2         3.0       0-2          1          2       1   
285  3.0          0         8.0       0-2          1          3       0   

     irradiat  Class  breast-quad_?  breast-quad_central  \
0           0      1            0.0                  0.0   
1           0      0            0.0                  1.0   
2           0      1            0.0                  0.0   
3           1      0            0.0                  0.0   
4           0      1            0.0                  0.0   
..        ...    ...            ...                  ...   
281         0      0            0.0                  0.0   
282         1      0            0.0                  0.0   
283         0      0            0.0                  0.0   
284         0      0            0.0                  0.0   
285         0      0            0.0                  0.0   

     breast-quad_left_low  breast-quad_left_up  breast-quad_right_low  \
0                     0.0                  1.0                    0.0   
1                     0.0                  0.0                    0.0   
2                     1.0                  0.0                    0.0   
3                     1.0                  0.0                    0.0   
4                     0.0                  0.0                    0.0   
..                    ...                  ...                    ...   
281                   1.0                  0.0                    0.0   
282                   1.0                  0.0                    0.0   
283                   0.0                  0.0                    0.0   
284                   1.0                  0.0                    0.0   
285                   0.0                  0.0                    0.0   

     breast-quad_right_up  
0                     0.0  
1                     0.0  
2                     0.0  
3                     0.0  
4                     1.0  
..                    ...  
281                   0.0  
282                   0.0  
283                   1.0  
284                   0.0  
285                   1.0  

[286 rows x 15 columns]

In [99]:
oe = OrdinalEncoder(categories=[['0-2','3-5','6-8','9-11', '12-14', '15-17','24-26']])
base['inv-nodes'] = oe.fit_transform(base[['inv-nodes']])
base = base.drop_duplicates()
base2 = base.drop('Class', axis=1)
base

age  menopause  tumor-size  inv-nodes  node-caps  deg-malig  breast  \
0    2.0          2         3.0        0.0          2          3       1   
1    3.0          0         3.0        0.0          1          1       1   
2    3.0          0         7.0        0.0          1          2       0   
3    2.0          2         7.0        0.0          2          3       1   
4    2.0          2         6.0        1.0          2          2       0   
..   ...        ...         ...        ...        ...        ...     ...   
281  3.0          0         6.0        2.0          2          2       0   
282  3.0          2         5.0        1.0          2          2       0   
283  1.0          2         6.0        2.0          2          2       1   
284  3.0          2         3.0        0.0          1          2       1   
285  3.0          0         8.0        0.0          1          3       0   

     irradiat  Class  breast-quad_?  breast-quad_central  \
0           0      1            0.0                  0.0   
1           0      0            0.0                  1.0   
2           0      1            0.0                  0.0   
3           1      0            0.0                  0.0   
4           0      1            0.0                  0.0   
..        ...    ...            ...                  ...   
281         0      0            0.0                  0.0   
282         1      0            0.0                  0.0   
283         0      0            0.0                  0.0   
284         0      0            0.0                  0.0   
285         0      0            0.0                  0.0   

     breast-quad_left_low  breast-quad_left_up  breast-quad_right_low  \
0                     0.0                  1.0                    0.0   
1                     0.0                  0.0                    0.0   
2                     1.0                  0.0                    0.0   
3                     1.0                  0.0                    0.0   
4                     0.0                  0.0                    0.0   
..                    ...                  ...                    ...   
281                   1.0                  0.0                    0.0   
282                   1.0                  0.0                    0.0   
283                   0.0                  0.0                    0.0   
284                   1.0                  0.0                    0.0   
285                   0.0                  0.0                    0.0   

     breast-quad_right_up  
0                     0.0  
1                     0.0  
2                     0.0  
3                     0.0  
4                     1.0  
..                    ...  
281                   0.0  
282                   0.0  
283                   1.0  
284                   0.0  
285                   1.0  

[272 rows x 15 columns]

**Separando os atributos de entrada e de classe**

In [100]:
X_prev = base2.iloc[:, :].values

In [101]:
X_prev

array([[2., 2., 3., ..., 1., 0., 0.],
       [3., 0., 3., ..., 0., 0., 0.],
       [3., 0., 7., ..., 0., 0., 0.],
       ...,
       [1., 2., 6., ..., 0., 0., 1.],
       [3., 2., 3., ..., 0., 0., 0.],
       [3., 0., 8., ..., 0., 0., 1.]])

In [102]:
X_prev_label = base2.iloc[:, :]

In [103]:
X_prev_label

age  menopause  tumor-size  inv-nodes  node-caps  deg-malig  breast  \
0    2.0          2         3.0        0.0          2          3       1   
1    3.0          0         3.0        0.0          1          1       1   
2    3.0          0         7.0        0.0          1          2       0   
3    2.0          2         7.0        0.0          2          3       1   
4    2.0          2         6.0        1.0          2          2       0   
..   ...        ...         ...        ...        ...        ...     ...   
281  3.0          0         6.0        2.0          2          2       0   
282  3.0          2         5.0        1.0          2          2       0   
283  1.0          2         6.0        2.0          2          2       1   
284  3.0          2         3.0        0.0          1          2       1   
285  3.0          0         8.0        0.0          1          3       0   

     irradiat  breast-quad_?  breast-quad_central  breast-quad_left_low  \
0           0            0.0                  0.0                   0.0   
1           0            0.0                  1.0                   0.0   
2           0            0.0                  0.0                   1.0   
3           1            0.0                  0.0                   1.0   
4           0            0.0                  0.0                   0.0   
..        ...            ...                  ...                   ...   
281         0            0.0                  0.0                   1.0   
282         1            0.0                  0.0                   1.0   
283         0            0.0                  0.0                   0.0   
284         0            0.0                  0.0                   1.0   
285         0            0.0                  0.0                   0.0   

     breast-quad_left_up  breast-quad_right_low  breast-quad_right_up  
0                    1.0                    0.0                   0.0  
1                    0.0                    0.0                   0.0  
2                    0.0                    0.0                   0.0  
3                    0.0                    0.0                   0.0  
4                    0.0                    0.0                   1.0  
..                   ...                    ...                   ...  
281                  0.0                    0.0                   0.0  
282                  0.0                    0.0                   0.0  
283                  0.0                    0.0                   1.0  
284                  0.0                    0.0                   0.0  
285                  0.0                    0.0                   1.0  

[272 rows x 14 columns]

In [104]:
X_prev[:,:]


array([[2., 2., 3., ..., 1., 0., 0.],
       [3., 0., 3., ..., 0., 0., 0.],
       [3., 0., 7., ..., 0., 0., 0.],
       ...,
       [1., 2., 6., ..., 0., 0., 1.],
       [3., 2., 3., ..., 0., 0., 0.],
       [3., 0., 8., ..., 0., 0., 1.]])

In [105]:
y_classe = base.iloc[:, 8].values

In [106]:
y_classe

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

**Podemos fazer esta mesma divisão (separar as variáveis de entrada e saída) usando os comandos abaixo**

In [107]:
#X = base.copy() 
#y = X.pop('Conclusao')
base.columns[8]

'Class'

In [108]:
X_prev[:,0]

array([2., 3., 3., 2., 2., 3., 3., 2., 2., 2., 3., 4., 3., 3., 2., 1., 3.,
       3., 3., 3., 4., 3., 2., 1., 3., 3., 4., 2., 4., 4., 3., 3., 2., 1.,
       2., 4., 2., 2., 1., 2., 4., 3., 3., 4., 2., 3., 3., 5., 3., 2., 5.,
       2., 3., 3., 3., 3., 1., 3., 2., 2., 2., 2., 1., 4., 3., 1., 3., 4.,
       4., 3., 1., 3., 3., 2., 2., 4., 3., 2., 2., 4., 1., 3., 2., 1., 3.,
       3., 4., 1., 3., 3., 3., 2., 1., 3., 4., 2., 2., 3., 3., 4., 2., 4.,
       4., 3., 3., 2., 4., 4., 1., 1., 4., 4., 2., 2., 2., 2., 3., 2., 1.,
       1., 3., 4., 4., 2., 4., 2., 0., 2., 2., 1., 1., 3., 3., 4., 3., 4.,
       2., 2., 3., 3., 3., 1., 4., 2., 3., 2., 3., 3., 1., 4., 4., 1., 1.,
       3., 4., 3., 2., 4., 3., 2., 3., 4., 2., 2., 2., 3., 3., 2., 3., 2.,
       2., 2., 2., 2., 1., 4., 2., 3., 2., 4., 2., 2., 3., 3., 2., 4., 4.,
       2., 1., 1., 4., 2., 4., 1., 2., 4., 2., 2., 4., 3., 3., 2., 2., 2.,
       2., 2., 3., 5., 4., 4., 3., 3., 2., 3., 1., 4., 4., 2., 1., 2., 1.,
       2., 3., 3., 4., 4.

In [109]:
X_prev

array([[2., 2., 3., ..., 1., 0., 0.],
       [3., 0., 3., ..., 0., 0., 0.],
       [3., 0., 7., ..., 0., 0., 0.],
       ...,
       [1., 2., 6., ..., 0., 0., 1.],
       [3., 2., 3., ..., 0., 0., 0.],
       [3., 0., 8., ..., 0., 0., 1.]])

In [110]:

#label_encoder_first_column = LabelEncoder()

In [111]:

#X_prev[:,0] = label_encoder_first_column.fit_transform(X_prev[:,0])


In [112]:
X_prev

array([[2., 2., 3., ..., 1., 0., 0.],
       [3., 0., 3., ..., 0., 0., 0.],
       [3., 0., 7., ..., 0., 0., 0.],
       ...,
       [1., 2., 6., ..., 0., 0., 1.],
       [3., 2., 3., ..., 0., 0., 0.],
       [3., 0., 8., ..., 0., 0., 1.]])



> OneHotEncoder - Agora vamos binarizar atributos não ordinais

**Contando quantas opções de resposta tem cada atributo**

In [113]:
#len(np.unique(base['Cliente'])) 

In [114]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [115]:
X_prev

array([[2., 2., 3., ..., 1., 0., 0.],
       [3., 0., 3., ..., 0., 0., 0.],
       [3., 0., 7., ..., 0., 0., 0.],
       ...,
       [1., 2., 6., ..., 0., 0., 1.],
       [3., 2., 3., ..., 0., 0., 0.],
       [3., 0., 8., ..., 0., 0., 1.]])

In [116]:
X_prev[:,0:9]

array([[2., 2., 3., ..., 1., 0., 0.],
       [3., 0., 3., ..., 1., 0., 0.],
       [3., 0., 7., ..., 0., 0., 0.],
       ...,
       [1., 2., 6., ..., 1., 0., 0.],
       [3., 2., 3., ..., 1., 0., 0.],
       [3., 0., 8., ..., 0., 0., 0.]])

In [117]:
#onehotencoder_restaurante = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [4,5,8,9])], remainder='passthrough')


In [118]:
#X_prev= onehotencoder_restaurante.fit_transform(X_prev)

In [119]:
#X_prev

In [120]:
X_prev.shape

(272, 14)

**Esta mesma transformação OneHotEncoder pode ser feita com o comando abaixo**

In [121]:
#base = pd.get_dummies(X_prev_label)
#base.head()

**Método de amostragem Holdout**

In [122]:
from sklearn.model_selection import train_test_split

In [123]:
X_prev

array([[2., 2., 3., ..., 1., 0., 0.],
       [3., 0., 3., ..., 0., 0., 0.],
       [3., 0., 7., ..., 0., 0., 0.],
       ...,
       [1., 2., 6., ..., 0., 0., 1.],
       [3., 2., 3., ..., 0., 0., 0.],
       [3., 0., 8., ..., 0., 0., 1.]])

In [124]:
y_classe

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [125]:
y_classe.shape

(272,)

In [126]:
#X_train_ds, X_test_ds, y_train_ds, y_test_ds = train_test_split(X, y, test_size=0.3, random_state=123, shuffle=True, stratify=y)
X_treino, X_teste, y_treino, y_teste = train_test_split(X_prev, y_classe, test_size = 0.20, random_state = 0)

In [127]:
X_treino.shape

(217, 14)

In [128]:
X_teste.shape

(55, 14)

In [129]:
X_teste

array([[ 2.,  0.,  6.,  0.,  1.,  2.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
         0.],
       [ 1.,  2.,  4.,  1.,  2.,  2.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,
         0.],
       [ 2.,  0.,  6.,  1.,  1.,  3.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.],
       [ 4.,  0.,  2.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.],
       [ 3.,  2.,  5.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.],
       [ 4.,  0.,  5.,  1.,  1.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.],
       [ 3.,  2.,  2.,  0.,  1.,  2.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.],
       [ 3.,  0.,  1.,  0.,  1.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.],
       [ 3.,  0., 10.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.],
       [ 3.,  0.,  8.,  0.,  1.,  2.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.],
       [ 3.,  0.,  4.,  0.,  2.,  2.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.],
       [ 2.,  2.,  4.,  0.,  1.,  1.,  1., 

In [130]:
y_treino

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1])

In [131]:
y_teste

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [132]:
import pickle

In [133]:
with open('merge.pkl', mode = 'wb') as f:
  pickle.dump([X_treino, X_teste, y_treino, y_teste], f)